# Training and inference Parameters.
params = {
    'class_topk': 1000,
    'seed': 123456789,
    'lr': 1e-3,
    'batch_size': 32,
    'test_batch_size': 64,
    'optimizer': 'momentum',
    'epochs': 30,
    'scaleup_epochs': 0,
    'wd': 1e-5,
    'model_name': 'resnet101',
    'pooling': 'GeM',
    'use_fc': True,
    'loss': 'arcface',
    'margin': 0.3,
    's': 30,
    'theta_zero': 1.25,
    'fc_dim': 512,
    'scale_limit': 0.2,
    'shear_limit': 0,
    'brightness_limit': 0.0,
    'contrast_limit': 0.0,
    'augmentation': 'soft',
    'train_data': 'gld_v2',
    'freeze_bn': True,
    'verifythresh': 30,
    'freqthresh': 3
}
